[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"

[[edge_functions]]
  path = "/events"
  function = "event-schema"

[[edge_functions]]
  path = "/tickets"
  function = "event-schema"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
